# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Quotely' do
pod 'Alamofire', '~> 3.4'
pod 'Nuke'
pod 'Nuke-Alamofire-Plugin'
pod 'RealmSwift'
pod 'SwiftyJSON'
end

